### ISSUE TITLE
StackOverflowError in CoberturaReporter

### ISSUE THREAD

**Issue by balagez** [mtkopone/scct#27]
I have a generated .scala file with ~4000 lines (of which ~600 lines are effective in 36 classes) which compiles successfully. HTML report is successfully generated (the resulting file is around 500k) but Cobertura report generation dies with a StackOverflowError:

```
Exception in thread "Thread-9" java.lang.StackOverflowError
    at reaktor.scct.report.CoberturaReporter$$anonfun$2.<init>(CoberturaReporter.scala:48)
    at reaktor.scct.report.CoberturaReporter.line(CoberturaReporter.scala:48)
    at reaktor.scct.report.CoberturaReporter.line(CoberturaReporter.scala:55)
    at reaktor.scct.report.CoberturaReporter.line(CoberturaReporter.scala:55)
    at reaktor.scct.report.CoberturaReporter.line(CoberturaReporter.scala:55)
    at reaktor.scct.report.CoberturaReporter.line(CoberturaReporter.scala:55)
    at reaktor.scct.report.CoberturaReporter.line(CoberturaReporter.scala:55)
    at reaktor.scct.report.CoberturaReporter.line(CoberturaReporter.scala:55)
    ...
```

Environment:
scala 2.9.1
sbt 0.11.3
sbt-scct 0.2-SNAPSHOT

**Comment by mtkopone** [comment]
Hi, and thanks for the report.

CoberturaReporter was missing a tailrec-annotation. 

This has been fixed in https://github.com/mtkopone/scct/commit/44d6e330d6d45df560a80e35ff02a86dad21c779 and the fix is available in the new binaries. 

Thanks,
