### ISSUE TITLE
Hang with Scala 2.9.0.RC1

### ISSUE THREAD

**Issue by inkytonik** [mtkopone/scct#8]
When I use scct

```
lazy val scctPlugin = "reaktor" % "sbt-scct-for-2.8" % "0.1-SNAPSHOT"
```

with sbt 0.7.5 with a Scala 2.9.0.RC1 project, it hangs waiting for report completion.  The trace is

> test-coverage
> Setting props for kiama
> Generating report for kiama
> Wait for report completion.

With the same project and same sbt version selecting Scala 2.8.1 the report is produced very quickly.  With 2.9.0.RC1 it appears to be deadlocked.  (I've waiting hours, just in case...)

jstack reports the stack of the relevant thread to be:

"Thread-68" prio=5 tid=112c26000 nid=0x10f3c6000 waiting on condition [10f3c5000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
    at java.lang.Thread.sleep(Native Method)
    at reaktor.scct.ScctProject$class.reportNow(ScctProject.scala:55)
    at KiamaProject.reportNow(KiamaProject.scala:30)
    at reaktor.scct.ScctProject$$anonfun$instrumentedTestOptions$2.apply(ScctProject.scala:41)
    at reaktor.scct.ScctProject$$anonfun$instrumentedTestOptions$2.apply(ScctProject.scala:41)
    at sbt.ScalaProject$TestCleanup$$anonfun$apply$7.apply(ScalaProject.scala:78)
    at sbt.ScalaProject$TestCleanup$$anonfun$apply$7.apply(ScalaProject.scala:78)
    at sbt.TestFramework$$anonfun$createTasks$1$$anonfun$apply$9.apply(TestFramework.scala:166)
    at sbt.TestFramework$$anonfun$createTasks$1$$anonfun$apply$9.apply(TestFramework.scala:166)
    at sbt.NamedTestTask.run(TestFramework.scala:92)
    at sbt.ScalaProject$$anonfun$sbt$ScalaProject$$toTask$1.apply(ScalaProject.scala:193)
    at sbt.ScalaProject$$anonfun$sbt$ScalaProject$$toTask$1.apply(ScalaProject.scala:193)
    at sbt.TaskManager$Task.invoke(TaskManager.scala:62)
    at sbt.impl.RunTask.doRun$1(RunTask.scala:77)
    at sbt.impl.RunTask.runTask(RunTask.scala:85)
    at sbt.impl.RunTask.sbt$impl$RunTask$$runIfNotRoot(RunTask.scala:60)
    at sbt.impl.RunTask$$anonfun$runTasksExceptRoot$2.apply(RunTask.scala:48)
    at sbt.impl.RunTask$$anonfun$runTasksExceptRoot$2.apply(RunTask.scala:48)
    at sbt.Distributor$Run$Worker$$anonfun$2.apply(ParallelRunner.scala:131)
    at sbt.Distributor$Run$Worker$$anonfun$2.apply(ParallelRunner.scala:131)
    at sbt.Control$.trapUnit(Control.scala:19)
    at sbt.Distributor$Run$Worker.run(ParallelRunner.scala:131)

**Comment by mtkopone** [comment]
Hi, 

Yep, scct is not compatible with 2.9 yet. 

But here's a fork by paulp that (to my knowledge) is: 
https://github.com/paulp/scct

Let me know if that helps.

Cheers,

**Comment by inkytonik** [comment]
Thanks for the pointer.  I tried paulp's fork, but I have the same hang there.  When I get a bit more time I'll look into it more deeply, but for the moment I'll stick with the 2.8 version.

Tony

**Comment by glenford** [comment]
Have done some playing around and can see that the background thread is never being started, so the plugin sits waiting for the reporting flag i.e... while (System.getProperty(reportProperty) != "done") Thread.sleep(200)

Coverage init etc is never called.. am not sure why as yet

**Comment by mtkopone** [comment]
Since scala 2.9 is already out, I'll find time to fix scct to work with it.

glenford & inkytonic: Have you got an open-source project with a build that currently fails with scct? If so, can you give me a link to it so I could use it as a starting point?

**Comment by inkytonik** [comment]
Great, thanks.  Yep, our Kiama project is such a project.  See the transcript at:

https://gist.github.com/995153

It seems that the behaviour is a crash now with 2.9.0.

**Comment by glenford** [comment]
I can build scct with some minor changes against 2.9.0 - running coverage it will hang waiting for the report generation as mentioned above.

If I run the scct tests there are lots of errors - just starting to look at those

If I get a chance I will make a project available

**Comment by mtkopone** [comment]
Hi all, 

The latest version should now run under at least scala 2.9.0-1.
(As a smoke-test, I ran it on the Kiama project.)

Instructions for using the 2.9 branch can be found here: 
http://mtkopone.github.com/scct/

**Note** that when switching to the 2.9 branch, the name of the sbt plugin has changed in addition to the version:
`prev: sbt-scct-for-2.8`
`now :  scct-sbt-for-2.9`

**Comment by glenford** [comment]
Awesome stuff, much appreciated :)

**Comment by inkytonik** [comment]
Thanks!  The 2.9 version seems to be working for me.

**Comment by marcel** [comment]
Hanging for me using all three available versions of scct on Scala 2.8.1.

**Comment by marcel** [comment]
It turns out the hanging problem was specific to my environment.

**Comment by Anjaiah** [comment]
Hi, I am trying to do code coverage analysis:
1. Added this to my Build.scala
   seq(ScctPlugin.instrumentSettings : _*)
2.  added below depnedancy at plugin.sbt

resolvers += Classpaths.typesafeResolver

resolvers += "scct-github-repository" at "http://mtkopone.github.com/scct/maven-repo"

addSbtPlugin("reaktor" % "sbt-scct" % "0.2-SNAPSHOT")

I was able to do clean and compile but when I ran  sbt clean scct:test

Getting the following error: 
[success] Total time: 0 s, completed May 7, 2013 1:58:35 PM
[error] No such setting/task
[error] scct:test
[error]          ^

could you please guide me? 

I am using the scalaVersion := "2.10.1"
sbt sbt 0.12
